source 'https://cdn.cocoapods.org'
source 'https://gitee.com/jingshionline/jsolspecs.git'

inhibit_all_warnings!
use_frameworks!
platform :ios, '9.0'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
          end
      end
  end

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
