source 'https://cdn.cocoapods.org/'
source 'https://code.jingshonline.net/jingshonline/app/jsonlinespecs.git'
use_frameworks!

platform :ios, '9.0'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
